### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-twilio-source#1]
**Description**
This integration should pull data from Twilio's basic REST API to start. 

**Requirements**
- [ ] Authenticate through basic HTTP 
- [ ] Handle pagination of reponses
- [ ] Include optional config parameter (e.g. `format: json`) to[ return either JSON or XML](https://www.twilio.com/docs/api/rest/response) where available.
- [ ] Include optional config to pass in [date filter](https://www.twilio.com/docs/api/rest/recording#list-get-filters) where available.
- [ ] Method to:
  - [ ] [Get all Addresses](https://www.twilio.com/docs/api/rest/addresses#list-get)
  - [ ] [ Get available phone numbers](https://www.twilio.com/docs/api/rest/available-phone-numbers)
  - [ ] [Get all calls](https://www.twilio.com/docs/api/rest/call#list-get-example-1)
  - [ ] [Get call summaries](https://www.twilio.com/docs/api/rest/call-feedback#summary-list)
  - [ ] [Get conference lines](https://www.twilio.com/docs/api/rest/conference#list-get)
  - [ ] [List Incoming Phone Numbers](https://www.twilio.com/docs/api/rest/incoming-phone-numbers#list-get)
  - [ ] [Get All Messages](https://www.twilio.com/docs/api/rest/message#list-get)
  - [ ] [List outgoing call ID](https://www.twilio.com/docs/api/rest/outgoing-caller-ids#list-get-example-1)
  - [ ] [Get Queue](https://www.twilio.com/docs/api/rest/queue#list-get-example-1)
  - [ ] [Get all Recordings](https://www.twilio.com/docs/api/rest/recording#list-get-example-1) 
  - [ ] [Get Short Codes](https://www.twilio.com/docs/api/rest/short-codes#list-get)
  - [ ] [Get Usage Records](https://www.twilio.com/docs/api/rest/usage-records)
  - [ ] [Get Usage Triggers](https://www.twilio.com/docs/api/rest/usage-triggers#list-uri)

**Relevant Links**
https://www.twilio.com/docs/api/rest
https://www.twilio.com/docs/libraries/node

**Comment by austin-toot** [comment]
@trong-le @beckysteele This is done. Needs a full code review, but I didn't make a dev branch because I'm dumb, so no pull request.

**Comment by ryw** [comment]
no more work on aries
